- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v2.1.0
  hooks:
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: pretty-format-json
      args:
        - --autofix
    - id: trailing-whitespace

- repo: https://github.com/prettier/prettier
  rev: "1.16.4" # Use the sha or tag you want to point at
  hooks:
    - id: prettier
      args:
        - --write
        - src/
