title: Mukul's Personal Blog
description: A blog about Deep Learning and all things Computer Science!
plugins:
<<<<<<< HEAD
  - jekyll-feed
baseurl: /
=======
  - jekyll-feed      
  - jekyll-seo-tag
baseurl: /

>>>>>>> b57ebb5... Reset Google Analytics tracking
